spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password: sa
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
logging:
  level:
    liquibase: INFO
